version: "3.7"

services:

    simplestore-productcatalog:
        image: simplestore-productcatalog:dev
        build:
            context: .
            dockerfile: src/Services/ProductCatalog/SimpleStore.ProductCatalogApi/Dockerfile

    simplestore-inventories:
        image: simplestore-inventories:dev
        build:
            context: .
            dockerfile: src/Services/Inventories/SimpleStore.InventoriesApi/Dockerfile

    simplestore-graphql:
        image: simplestore-graphql:dev
        build:
            context: .
            dockerfile: src/Services/GraphQL/SimpleStore.GraphQLApi/Dockerfile
