version: "3.7"

services:

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: on-failure
        networks:
            - simple-microservices
        environment:
            SA_PASSWORD: "P@ssword"
            ACCEPT_EULA: "Y"
        ports:
            - "14333:1433"

    simplestore-productcatalog:
        ports:
            - "5011:5011" #http
        restart: on-failure
        environment: 
            - ASPNETCORE__ENVIRONMENT=Production
            - Services__GraphQLApi__RestUri=http://simplestore-graphql:5010
            - Services__ProductCatalogApi__RestUri=http://simplestore-productcatalog:5011
            - Services__InventoriesApi__RestUri=http://simplestore-inventories:5012
            - Redis__RedisAddress=redis:6379
            - DatabaseInformation__Server=sqlserver
            - DatabaseInformation__AccountPassword=P@ssword
        networks:
            - simple-microservices
        depends_on:
            - sqlserver
            - redis

    simplestore-inventories:
        ports:
            - "5012:5012" #http
        restart: on-failure
        environment: 
            - ASPNETCORE__ENVIRONMENT=Production
            - Services__GraphQLApi__RestUri=http://simplestore-graphql:5010
            - Services__ProductCatalogApi__RestUri=http://simplestore-productcatalog:5011
            - Services__InventoriesApi__RestUri=http://simplestore-inventories:5012
            - Redis__RedisAddress=redis:6379
            - DatabaseInformation__Server=sqlserver
            - DatabaseInformation__AccountPassword=P@ssword
        networks:
            - simple-microservices
        depends_on:
            - sqlserver
            - redis

    simplestore-graphql:
        ports:
            - "5010:5010" #http
        restart: on-failure
        environment: 
            - ASPNETCORE__ENVIRONMENT=Production
            - Services__GraphQLApi__RestUri=http://simplestore-graphql:5010
            - Services__ProductCatalogApi__RestUri=http://simplestore-productcatalog:5011
            - Services__InventoriesApi__RestUri=http://simplestore-inventories:5012
        networks:
            - simple-microservices
        depends_on:
            - simplestore-productcatalog
            - simplestore-inventories

networks:
    simple-microservices:
        name: simple-microservices-network
