version: "3.7"

services:

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: on-failure
        networks:
            - simple-microservices
        environment:
            SA_PASSWORD: "P@ssword"
            ACCEPT_EULA: "Y"
        ports:
            - "14333:1433"

networks:
    simple-microservices:
        name: simple-microservices-network