# Default values for graphql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: simplestore-graphqlapi:dev
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 5000

services:
  productcatalog: "http://simplestore-productcatalogapi:5001"
  inventories: "http://simplestore-inventoriesapi:5002"