# Default values for inventories-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: simplestore-inventoriesapi:dev
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5002

database:
  server: "simplestore-sqlserver,14333"
  password: "P@ssword"