apiVersion: v1
kind: Service
metadata:
  name: {{ include "simplestore-sqlserver.fullname" . }}
  labels:
    {{- include "simplestore-sqlserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mssql
      protocol: TCP
      name: mssql
  selector:
    {{- include "simplestore-sqlserver.selectorLabels" . | nindent 4 }}
